id = "rpl"
name = "RPL"
version = "0.2.3"
schema_version = 1
authors = ["Martin Strutinski"]
description = "Running Pseudo Language support for Zed"
repository = "https://github.com/sidequest-chain/rpl"
themes = []
icon_themes = []
languages = ["languages/rpl"]
capabilities = []

[language_servers.rpl]
name = "rpl"
languages = ["RPL"]

[context_servers]

[slash_commands]
